apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sabbourazchcaptureorder 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sabbourazchcaptureorder 
    spec:
      containers:
        - name: sabbourazchcaptureorder 
          image: sabbour.azurecr.io/sabbourazchcaptureorder 
          ports:
          - containerPort: 8080